variable "system" {}
variable "env" {}
variable "name_prefix" {}
variable "subnets" {}
variable "security_groups" {}
variable "target_group" {}
variable "web_task_role" {}
variable "web_task_execute_role" {}
variable "task_definition_application" {}
variable "ecr_repo_web" {}
variable "ecr_repo_app" {}
variable "log_group_name_application" {}